/*eslint-disable*/

/*
  This is an example object that will match the shape of the poll report
  generated by the usePollData hook (this has yet to be implemented).
  
  It embeds an array of questions with the results of the "calculateAndSetAnswerTally"
  function from the useQuestionData hook. Due to this, the "labels" represent the 
  answerOptions, and the "data" corresponds to the answer count for the option
  at the same index.

  THIS SHOULD BE DELETED/EXCLUDED FROM PRODUCTION CODE AFTER REAL DATA EXISTS
*/

export const pollReport = {
  title: "Test Poll Report", // poll.title
  createdAt: "02-23-2023", //poll.createdAt - this is an arbitrary datetime string right now
  questions: [
    {
      prompt: "Are you left-handed or right-handed?", //question.prompt
      answerTally: {
        labels: ["Right-handed", "Left-handed"], // generated from question.answerOptions
        data: [13,7], // maps to sum of each answer 
      }
    },
    {
      prompt: "Yankees or Mets?", //question.prompt
      answerTally: {
        labels: ["Yankees", "Mets"], // generated from question.answerOptions
        data: [3,17], // maps to sum of each answer 
      }
    },
    {
      prompt: "Which instrument do you want to study?", //question.prompt
      answerTally: {
        labels: ["Guitar", "Bass", "Piano", "Drums"], // generated from question.answerOptions
        data: [6,4,3,7], // maps to sum of each answer 
      }
    },
    {
      prompt: "What's your favorite major US sport?", //question.prompt
      answerTally: {
        labels: ["Baseball", "Football", "Basketball", "Soccer"], // generated from question.answerOptions
        data: [7,3,5,5], // maps to sum of each answer 
      }
    },
    {
      prompt: "Where is your favorite place to live?", //question.prompt
      answerTally: {
        labels: ["City", "Suburbs", "Country"], // generated from question.answerOptions
        data: [8,5,7], // maps to sum of each answer 
      }
    },
  ]
};
