name: Build and Deploy to S3 Bucket

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: development
    
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-1 # optional: defaults to us-east-1
      SOURCE_DIR: bundle # optional: defaults to public
      REGION: us-west-2
      DIST: build
      DIST_ID: ${{ secrets.DIST_ID }}
    
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    
    - uses: actions/checkout@main
    
    - uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
        
    - name: Install Dependencies
      run: |
        node --version
        npm ci --production
        
    - name: Build static website
      run: npm run build
      
    - name: Copy files to the production website via AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.AWS_S3_BUCKET }}
        
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"

